on:
  # schedule: 
  #   # runs once a week on sunday
  #   - cron: "55 23 * * 0"
  push:
    branches:
      - main
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "" # The branch that you want to checkout. 
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: |
           pwd
           ls
           python3 data_acquisition_script.py ${{ GITHUB_TOKEN }}
    # # Calculates traffic and clones and stores in CSV file
    # - name: GitHub traffic 
    #   uses: anshsingal/repository-traffic-action@v.0.1.6
    #   env:
    #     TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
    # # Commits files to repository
    # - name: Commit changes
    #   uses: EndBug/add-and-commit@v4
    #   with:
    #     author_name: Santiago Gonzalez
    #     message: "GitHub traffic"
    #     add: "./traffic/*"
    #     ref: "traffic"  # commits to branch "traffic" 
